### ISSUE TITLE
How to properly credit you? 

### ISSUE THREAD

**Issue by TheHappyKoala** [bpodgursky/uncharted#4]
Hey!

Big fan of your project. I've put your star shader into use in my gravity simulator - https://gravitysimulator.org/solar-system/the-earth-system - and while it's not of much use at the moment since most of the scenarios are solar system ones, I'm about to add a whole bunch of scenarios created from exoplanet archive data, and since this data includes star temperatures, your shader will make things a great deal cooler and realistic. 

How do I properly credit you? Do I include your license in the build? Is it compatible with the GNU General Public License v3.0? Also, if you want to be included on the credits page (https://gravitysimulator.org/credits), let me know! You will find the repo for my project here: https://github.com/TheHappyKoala/Harmony-of-the-Spheres

Cheers,

Darrell

**Comment by bpodgursky** [comment]
Super cool, thanks for the note!

The license is Apache 2.0, which is compatible with GPL 3.0, yes: https://www.gnu.org/licenses/license-list.en.html#apache2

I think normal for Apache 2.0 is to just include the short form of the license next to the included code (this blob https://github.com/bpodgursky/uncharted/blob/master/LICENSE.txt), and link back to the original in the source if you want.  

I'm flattered by the idea of a credit, but I don't think I did nearly enough work to make it onto that list : ) Good luck with the project!

**Comment by TheHappyKoala** [comment]
Awesome, cheers for getting back to me so quickly.

I've added the short version of the license to the module with the shader code: https://github.com/TheHappyKoala/Harmony-of-the-Spheres/blob/migrate_to_gatsby/src/scene/shaders/star.ts

Gonna add a resource section to the readme later on this week and will link to your project there.

On that note, happy new year 🚀

**Comment by bpodgursky** [comment]
Happy new year!
